<?php

// Your API Key and secret
$apiKey = "t5xmkjtsncnet9p9qcfkty7z";
$Secret = "gphJhG2dC4";

// Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
$signature = hash("sha256", $apiKey.$Secret.time());

$endpoint = "https://api.test.hotelbeds.com/hotel-content-api/1.0/hotels?fields=all&language=ENG&from=1&to=500&lastUpdateTime=2019-10-10";

echo "Your API Key is: " . $apiKey . "";
echo "Your X-Signature is: " . $signature . "";

// Example of call to the API
try
{	
	// Get cURL resource
	$curl = curl_init();
	// Set some options 
	curl_setopt_array($curl, array(
	CURLOPT_RETURNTRANSFER => 1,
	CURLOPT_URL => $endpoint,
	CURLOPT_HTTPHEADER => ['Accept:application/json' , 'Api-key:'.$apiKey.'', 'X-Signature:'.$signature.'']
	));
	// Send the request & save response to $resp
	$resp = curl_exec($curl);

	// Check HTTP status code
	if (!curl_errno($curl)) {
		switch ($http_code = curl_getinfo($curl, CURLINFO_HTTP_CODE)) {
			case 200:  # OK
				echo "Server JSON Response:" . $resp;
				break;
			default:
				echo 'Unexpected HTTP code: ', $http_code, "\n";
				echo $resp;
		}
	}
	
	// Close request to clear up some resources
	curl_close($curl);


} catch (Exception $ex) {

	printf("Error while sending request, reason: %s\n",$ex->getMessage());

}
?>