-- ============================================================================
-- 2026-05-add-pk-sequences-fnd.sql
--
-- Add auto-increment behavior to primary-key columns that were originally
-- MySQL AUTO_INCREMENT but were created on SQL Server WITHOUT IDENTITY.
-- INSERTs that omit the PK column were failing with:
--   "Cannot insert the value NULL into column 'user_fnd_id' ..."
--
-- Approach: SEQUENCE + DEFAULT instead of IDENTITY, because IDENTITY cannot
-- be added to an existing column via ALTER COLUMN in SQL Server (would
-- require drop-and-recreate of the table). SEQUENCE+DEFAULT is one-shot,
-- preserves all existing rows, and requires no FK changes.
--
-- After running this script, INSERTs that don't supply user_fnd_id / id
-- get the next sequence value automatically.
--
-- Caveat: SCOPE_IDENTITY() does NOT return values generated by a SEQUENCE
-- default. Code paths that need the new ID must either:
--   (a) re-query (SELECT user_fnd_id WHERE user_key = '...')  -- the pattern
--       add_new_customer.php already uses; or
--   (b) use INSERT ... OUTPUT INSERTED.user_fnd_id INTO @var
-- Avoid relying on $con->insert_id() for these two tables.
-- ============================================================================

SET NOCOUNT ON;

-- ----------------------------------------------------------------------------
-- fnd_user_profile.user_fnd_id
-- ----------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = 'seq_fnd_user_profile_id')
BEGIN
    DECLARE @start_fnd BIGINT;
    SELECT @start_fnd = ISNULL(MAX(user_fnd_id), 0) + 1 FROM fnd_user_profile;
    DECLARE @sql_fnd NVARCHAR(MAX) =
        N'CREATE SEQUENCE dbo.seq_fnd_user_profile_id AS BIGINT START WITH '
        + CAST(@start_fnd AS NVARCHAR(20))
        + N' INCREMENT BY 1 NO CACHE';
    EXEC sp_executesql @sql_fnd;
    PRINT 'Created SEQUENCE dbo.seq_fnd_user_profile_id starting at ' + CAST(@start_fnd AS NVARCHAR(20));
END
ELSE
    PRINT 'SEQUENCE dbo.seq_fnd_user_profile_id already exists.';

IF NOT EXISTS (
    SELECT 1 FROM sys.default_constraints
    WHERE name = 'DF_fnd_user_profile_user_fnd_id'
)
BEGIN
    ALTER TABLE fnd_user_profile
        ADD CONSTRAINT DF_fnd_user_profile_user_fnd_id
        DEFAULT NEXT VALUE FOR dbo.seq_fnd_user_profile_id
        FOR user_fnd_id;
    PRINT 'Added DEFAULT DF_fnd_user_profile_user_fnd_id.';
END
ELSE
    PRINT 'DEFAULT DF_fnd_user_profile_user_fnd_id already exists.';

-- ----------------------------------------------------------------------------
-- fnd_user_profile_submission.id
-- ----------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = 'seq_fnd_user_profile_submission_id')
BEGIN
    DECLARE @start_sub BIGINT;
    SELECT @start_sub = ISNULL(MAX(id), 0) + 1 FROM fnd_user_profile_submission;
    DECLARE @sql_sub NVARCHAR(MAX) =
        N'CREATE SEQUENCE dbo.seq_fnd_user_profile_submission_id AS BIGINT START WITH '
        + CAST(@start_sub AS NVARCHAR(20))
        + N' INCREMENT BY 1 NO CACHE';
    EXEC sp_executesql @sql_sub;
    PRINT 'Created SEQUENCE dbo.seq_fnd_user_profile_submission_id starting at ' + CAST(@start_sub AS NVARCHAR(20));
END
ELSE
    PRINT 'SEQUENCE dbo.seq_fnd_user_profile_submission_id already exists.';

IF NOT EXISTS (
    SELECT 1 FROM sys.default_constraints
    WHERE name = 'DF_fnd_user_profile_submission_id'
)
BEGIN
    ALTER TABLE fnd_user_profile_submission
        ADD CONSTRAINT DF_fnd_user_profile_submission_id
        DEFAULT NEXT VALUE FOR dbo.seq_fnd_user_profile_submission_id
        FOR id;
    PRINT 'Added DEFAULT DF_fnd_user_profile_submission_id.';
END
ELSE
    PRINT 'DEFAULT DF_fnd_user_profile_submission_id already exists.';

PRINT 'Migration complete.';

-- ============================================================================
-- ROLLBACK (if needed)
-- ============================================================================
-- ALTER TABLE fnd_user_profile             DROP CONSTRAINT DF_fnd_user_profile_user_fnd_id;
-- ALTER TABLE fnd_user_profile_submission  DROP CONSTRAINT DF_fnd_user_profile_submission_id;
-- DROP SEQUENCE dbo.seq_fnd_user_profile_id;
-- DROP SEQUENCE dbo.seq_fnd_user_profile_submission_id;
